# escape delay causes issues in nvim
set -s escape-time 0
set-option -sg escape-time 0

# support OSC 52 clipboard
set -s set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'
